// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtSIMU2ivQMDe-e__13HaY58IJQZaQ9O4',
    appId: '1:260301549772:web:f796a06307c0fa3c6e5269',
    messagingSenderId: '260301549772',
    projectId: 'geosnap-8a9cc',
    authDomain: 'geosnap-8a9cc.firebaseapp.com',
    storageBucket: 'geosnap-8a9cc.appspot.com',
    measurementId: 'G-E0FS1VVTNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-G4fV3iliYkzzPDwe4CumoR5hAe5ZRSs',
    appId: '1:260301549772:android:7b1761010955ae046e5269',
    messagingSenderId: '260301549772',
    projectId: 'geosnap-8a9cc',
    storageBucket: 'geosnap-8a9cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg_iTVPhHAnDq2xFmUvQ3V4QrydgMUl6k',
    appId: '1:260301549772:ios:fb3541af27d105796e5269',
    messagingSenderId: '260301549772',
    projectId: 'geosnap-8a9cc',
    storageBucket: 'geosnap-8a9cc.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg_iTVPhHAnDq2xFmUvQ3V4QrydgMUl6k',
    appId: '1:260301549772:ios:fb3541af27d105796e5269',
    messagingSenderId: '260301549772',
    projectId: 'geosnap-8a9cc',
    storageBucket: 'geosnap-8a9cc.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtSIMU2ivQMDe-e__13HaY58IJQZaQ9O4',
    appId: '1:260301549772:web:6ded3bddaa7248dc6e5269',
    messagingSenderId: '260301549772',
    projectId: 'geosnap-8a9cc',
    authDomain: 'geosnap-8a9cc.firebaseapp.com',
    storageBucket: 'geosnap-8a9cc.appspot.com',
    measurementId: 'G-YFR8JBQ5LJ',
  );

}